//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MotorSurveySystem.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.CurrencyConvertionSoap")]
    public interface CurrencyConvertionSoap {
        
        // CODEGEN: Generating message contract since element name currencyCode from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConvertCurrency", ReplyAction="*")]
        MotorSurveySystem.ServiceReference2.ConvertCurrencyResponse ConvertCurrency(MotorSurveySystem.ServiceReference2.ConvertCurrencyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConvertCurrency", ReplyAction="*")]
        System.Threading.Tasks.Task<MotorSurveySystem.ServiceReference2.ConvertCurrencyResponse> ConvertCurrencyAsync(MotorSurveySystem.ServiceReference2.ConvertCurrencyRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConvertCurrencyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConvertCurrency", Namespace="http://tempuri.org/", Order=0)]
        public MotorSurveySystem.ServiceReference2.ConvertCurrencyRequestBody Body;
        
        public ConvertCurrencyRequest() {
        }
        
        public ConvertCurrencyRequest(MotorSurveySystem.ServiceReference2.ConvertCurrencyRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConvertCurrencyRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public decimal amount;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string currencyCode;
        
        public ConvertCurrencyRequestBody() {
        }
        
        public ConvertCurrencyRequestBody(decimal amount, string currencyCode) {
            this.amount = amount;
            this.currencyCode = currencyCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConvertCurrencyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConvertCurrencyResponse", Namespace="http://tempuri.org/", Order=0)]
        public MotorSurveySystem.ServiceReference2.ConvertCurrencyResponseBody Body;
        
        public ConvertCurrencyResponse() {
        }
        
        public ConvertCurrencyResponse(MotorSurveySystem.ServiceReference2.ConvertCurrencyResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConvertCurrencyResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public decimal ConvertCurrencyResult;
        
        public ConvertCurrencyResponseBody() {
        }
        
        public ConvertCurrencyResponseBody(decimal ConvertCurrencyResult) {
            this.ConvertCurrencyResult = ConvertCurrencyResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CurrencyConvertionSoapChannel : MotorSurveySystem.ServiceReference2.CurrencyConvertionSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CurrencyConvertionSoapClient : System.ServiceModel.ClientBase<MotorSurveySystem.ServiceReference2.CurrencyConvertionSoap>, MotorSurveySystem.ServiceReference2.CurrencyConvertionSoap {
        
        public CurrencyConvertionSoapClient() {
        }
        
        public CurrencyConvertionSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CurrencyConvertionSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CurrencyConvertionSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CurrencyConvertionSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MotorSurveySystem.ServiceReference2.ConvertCurrencyResponse MotorSurveySystem.ServiceReference2.CurrencyConvertionSoap.ConvertCurrency(MotorSurveySystem.ServiceReference2.ConvertCurrencyRequest request) {
            return base.Channel.ConvertCurrency(request);
        }
        
        public decimal ConvertCurrency(decimal amount, string currencyCode) {
            MotorSurveySystem.ServiceReference2.ConvertCurrencyRequest inValue = new MotorSurveySystem.ServiceReference2.ConvertCurrencyRequest();
            inValue.Body = new MotorSurveySystem.ServiceReference2.ConvertCurrencyRequestBody();
            inValue.Body.amount = amount;
            inValue.Body.currencyCode = currencyCode;
            MotorSurveySystem.ServiceReference2.ConvertCurrencyResponse retVal = ((MotorSurveySystem.ServiceReference2.CurrencyConvertionSoap)(this)).ConvertCurrency(inValue);
            return retVal.Body.ConvertCurrencyResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MotorSurveySystem.ServiceReference2.ConvertCurrencyResponse> MotorSurveySystem.ServiceReference2.CurrencyConvertionSoap.ConvertCurrencyAsync(MotorSurveySystem.ServiceReference2.ConvertCurrencyRequest request) {
            return base.Channel.ConvertCurrencyAsync(request);
        }
        
        public System.Threading.Tasks.Task<MotorSurveySystem.ServiceReference2.ConvertCurrencyResponse> ConvertCurrencyAsync(decimal amount, string currencyCode) {
            MotorSurveySystem.ServiceReference2.ConvertCurrencyRequest inValue = new MotorSurveySystem.ServiceReference2.ConvertCurrencyRequest();
            inValue.Body = new MotorSurveySystem.ServiceReference2.ConvertCurrencyRequestBody();
            inValue.Body.amount = amount;
            inValue.Body.currencyCode = currencyCode;
            return ((MotorSurveySystem.ServiceReference2.CurrencyConvertionSoap)(this)).ConvertCurrencyAsync(inValue);
        }
    }
}
